In [3]:
import pandas as pd
obj=pd.Series([2,1,5,4,0.6,-4])
obj[2]

5.0

In [3]:
obj=pd.Series([2,3,1,5,6,3],index=['a','b','c','y','h','k'])
print(obj)
print(obj.values)#it return value
print(obj.index)

a    2
b    3
c    1
y    5
h    6
k    3
dtype: int64
[2 3 1 5 6 3]
Index(['a', 'b', 'c', 'y', 'h', 'k'], dtype='object')


In [5]:
print(obj['h'])
print(obj[['a','c','k']])

6
a    2
c    1
k    3
dtype: int64


In [10]:
print(obj[obj>2])#it returns value which greater then 2

b    3
y    5
h    6
k    3
dtype: int64


In [11]:
print(obj*3)

a     6
b     9
c     3
y    15
h    18
k     9
dtype: int64


In [14]:
print('b' in obj)
print('d' in obj)


True
False


In [6]:
data={'ohio':3,
      'texas':4,
      'Hamra':5
     }
print(pd.Series(data))
data['ohio']

ohio     3
texas    4
Hamra    5
dtype: int64


3

In [3]:
state=['ohio','Sugar','Hamra','Lemon']#there is ohio and Hamra match data and other does not
ob1=pd.Series(data,index=state)
ob1

ohio     3.0
Sugar    NaN
Hamra    5.0
Lemon    NaN
dtype: float64

In [24]:
print(pd.isnull(ob1))#sugar and Lemon is null because there is no Value

ohio     False
Sugar     True
Hamra    False
Lemon     True
dtype: bool


In [4]:
data={
    'ohio':1200,
    'texas':200,
    'Hamra':100
}
obj1=pd.Series(data)
print(obj1)
data1={
    'ohio':100,
    'texas':200,
    'Hamra':230,
    'lara' :2000
}
obj2=pd.Series(data1)
print(obj2)
print("After Addition")
obj1+obj2


ohio     1200
texas     200
Hamra     100
dtype: int64
ohio      100
texas     200
Hamra     230
lara     2000
dtype: int64
After Addition


Hamra     330.0
lara        NaN
ohio     1300.0
texas     400.0
dtype: float64

In [17]:
obj2.name='population' #updated
obj2

ohio     100
texas    200
Hamra    230
Name: population, dtype: int64

In [18]:
obj2.index.name='States' #Create index
obj2

States
ohio     100
texas    200
Hamra    230
Name: population, dtype: int64

In [22]:
obj #Create above
obj.index=['Texas','ohio','Karela','Us','naka','tap'] #list
obj

Texas     2.0
ohio      1.0
Karela    5.0
Us        4.0
naka      0.6
tap      -4.0
dtype: float64

# DATA FRAME

In [27]:
import pandas as pd
Data={
    'state':['Karachi','Lahore',"faisalabad","Rawalpindi"],#Arrays length must be same
    'Year':[2018,2019,2020,2021],
    'POp':[1.2,1.2,3.4,5.4]
}
frame=pd.DataFrame(Data)
frame

state  Year  POp
0     Karachi  2018  1.2
1      Lahore  2019  1.2
2  faisalabad  2020  3.4
3  Rawalpindi  2021  5.4

In [30]:
pd.DataFrame(Data,columns=['state','POp','Year']) #columns name as you want

state  POp  Year
0     Karachi  1.2  2018
1      Lahore  1.2  2019
2  faisalabad  3.4  2020
3  Rawalpindi  5.4  2021

In [8]:
frame2=pd.DataFrame(Data,columns=['Year','state','POp','debt'],index=['a','b',"c",'d'])
frame2

Year       state  POp debt
a  2018     Karachi  1.2  NaN
b  2019      Lahore  1.2  NaN
c  2020  faisalabad  3.4  NaN
d  2021  Rawalpindi  5.4  NaN

In [33]:
frame2.columns

Index(['Year', 'state', 'POp'], dtype='object')

In [34]:
frame2.state

a       Karachi
b        Lahore
c    faisalabad
d    Rawalpindi
Name: state, dtype: object

In [35]:
frame2.Year

a    2018
b    2019
c    2020
d    2021
Name: Year, dtype: int64

In [11]:
frame2.loc[['b','c','d']]
# it gives row wise data and accept index

Year       state  POp debt
b  2019      Lahore  1.2  NaN
c  2020  faisalabad  3.4  NaN
d  2021  Rawalpindi  5.4  NaN

In [13]:
frame2['debt']=16.5 # update value
frame2

Year       state  POp  debt
a  2018     Karachi  1.2  16.5
b  2019      Lahore  1.2  16.5
c  2020  faisalabad  3.4  16.5
d  2021  Rawalpindi  5.4  16.5

In [8]:
import numpy as np
frame2['debt']=np.arange(4)
frame2

Year       state  POp  debt
a  2018     Karachi  1.2     0
b  2019      Lahore  1.2     1
c  2020  faisalabad  3.4     2
d  2021  Rawalpindi  5.4     3

In [9]:
val=pd.Series([2.3,5.6,7.9],index=["a","d","c"]) #updating value with the help of index using Series 
frame2['debt']=val
frame2

Year       state  POp  debt
a  2018     Karachi  1.2   2.3
b  2019      Lahore  1.2   NaN
c  2020  faisalabad  3.4   7.9
d  2021  Rawalpindi  5.4   5.6

In [12]:
frame2['eastern']=frame2.state=='Karachi' #check which time karachi
frame2

Year       state  POp  debt  eastern
a  2018     Karachi  1.2   2.3     True
b  2019      Lahore  1.2   NaN    False
c  2020  faisalabad  3.4   7.9    False
d  2021  Rawalpindi  5.4   5.6    False

In [13]:
del frame2['eastern'] #dellete column eastern

In [14]:
frame2.columns #returns columns

Index(['Year', 'state', 'POp', 'debt'], dtype='object')

In [31]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, #Matching index
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [18]:
frame3.T #Return transpose

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [33]:
pd.DataFrame(pop,index=[2001,2002,2003]) #updating index

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [43]:
pdata={
    'Ohio':frame3['Ohio'][:-2],
    'Nevada':frame3["Nevada"][:]
}

In [44]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   NaN     NaN
2001   1.7     2.4
2002   NaN     2.9

In [43]:
frame3.index.name='year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [49]:
frame3.aggregate('Ohio')


year
2001    1.7
2002    3.6
2000    1.5
Name: Ohio, dtype: float64

In [51]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

# Index Objects

In [15]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
print(obj)
index = obj.index
print(index)

a    0
b    1
c    2
dtype: int64
Index(['a', 'b', 'c'], dtype='object')


In [23]:
index[:-1]

Index(['a', 'b'], dtype='object')

In [24]:
index[1] = 'd' 

TypeError: Index does not support mutable operations

In [47]:
import numpy as np
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [34]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels) # it means numpy index and panda index are same
obj2
obj2.index is labels

True

In [35]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, #Matching index
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [36]:
"Ohio" in frame3.columns

True

In [37]:
2003 in frame3.index


False

# Reindexing

In [21]:
import pandas as pd
#obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['3', '2', '1', '0'])
#obj
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [3]:
obj2=obj.reindex(['a','b','c','d'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [22]:
obj3.reindex(range(6), method='ffill')#fill only if index order is increasing or decreasing

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [25]:
import numpy as np
frame=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','b','c'],columns=['karachi','Islamabad','Queta'])
frame

karachi  Islamabad  Queta
a        0          1      2
b        3          4      5
c        6          7      8

In [28]:
frame.reindex(['b','c','a','e'])

karachi  Islamabad  Queta
b      3.0        4.0    5.0
c      6.0        7.0    8.0
a      0.0        1.0    2.0
e      NaN        NaN    NaN

In [29]:
state=['peshawar','hyderabad','karachi','Islamabad'] #reindexing on columns
frame.reindex(columns=state)

peshawar  hyderabad  karachi  Islamabad
a       NaN        NaN        0          1
b       NaN        NaN        3          4
c       NaN        NaN        6          7

# Dropping Entries from an Axis


In [50]:
dr=pd.Series(np.arange(5.),index=['a','b','d','d','d'])
print(dr)
dr.drop('d')#single droping

a    0.0
b    1.0
d    2.0
d    3.0
d    4.0
dtype: float64


a    0.0
b    1.0
dtype: float64

In [33]:
dr.drop(['a','c'])#multiple droping

b    1.0
d    3.0
e    4.0
dtype: float64

In [44]:
data=pd.DataFrame(np.arange(9).reshape(3,3),index=['a','b','c'],columns=['karachi','islamabad','queta'])
print(data)
print(data.drop('b'))#single index drop
print(data.drop(['a','c']))#multi index drop
print(data)#tamam data mujood hai

   karachi  islamabad  queta
a        0          1      2
b        3          4      5
c        6          7      8
   karachi  islamabad  queta
a        0          1      2
c        6          7      8
   karachi  islamabad  queta
b        3          4      5
   karachi  islamabad  queta
a        0          1      2
b        3          4      5
c        6          7      8


In [41]:
print(data.drop('karachi',axis=1)) #column drop or axis=1
print(data.drop(['karachi','islamabad'],axis=1))#multiple droping columns

   islamabad  queta
a          1      2
b          4      5
c          7      8
   queta
a      2
b      5
c      8


In [48]:
data.drop('a',inplace=True)#inplace method data ko modify kardeta hai
data

karachi  islamabad  queta
b        3          4      5
c        6          7      8

# Indexing, Selection, and Filtering

In [54]:
import numpy as np
data1=pd.Series(np.arange(4),index=['a','b','c','d'])
print(data1)
print(data1[[1,3,0]])#select with choice
print(data1[2:4])#select with slicing
print(data1[['b','d']])#select with labels

a    0
b    1
c    2
d    3
dtype: int32
b    1
d    3
a    0
dtype: int32
c    2
d    3
dtype: int32
b    1
d    3
dtype: int32


In [58]:
print(data1[data1<2])#filter values


a    0
b    1
dtype: int32


In [61]:
data1['a':'b']=4#updating values
data1

a    4
b    4
c    2
d    3
dtype: int32

In [51]:
import numpy as np
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three', 'four'])
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [53]:
print(data['two'])
print(data['two']>6)

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32
Ohio        False
Colorado    False
Utah         True
New York     True
Name: two, dtype: bool


In [73]:
print(data[:2])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7


In [76]:
data[data<5]=2#updating values
data

one  two  three  four
Ohio        2    2      2     2
Colorado    2    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

# Selection with loc and iloc

In [4]:
import numpy as np
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
columns=['one', 'two', 'three', 'four'])
print(data)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [11]:
print(data.loc['Ohio']) #select one column
print(data.loc['Utah',['one','three']])#select multiple column

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32
one       8
three    10
Name: Utah, dtype: int32


In [15]:
print(data.iloc[3,[1,0,2]])#iloc return integer value by index
print(data.iloc[0])#return by index

two      13
one      12
three    14
Name: New York, dtype: int32
one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32


In [7]:
print(data.iloc[[1,2],[0,1,3]])#multiple index select

          one  two  four
Colorado    4    5     7
Utah        8    9    11


In [10]:
data.loc[:'Ohio', 'three']

Ohio    2
Name: three, dtype: int32

In [57]:
data.iloc[:,2:][data.two > 9]

three  four
New York     14    15

# Integer Indexes


In [61]:
ser = pd.Series(np.arange(3.))
ser[-1]

KeyError: -1

In [64]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])# with a non-integer index, there is no potential for ambiguity
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [74]:
print(ser2[-2])
print(ser[:1])
print(ser.loc[:2])
print("******")
print(ser.iloc[:2])

1.0
0    0.0
dtype: float64
0    0.0
1    1.0
2    2.0
dtype: float64
******
0    0.0
1    1.0
dtype: float64


# Arithmetic and Data Alignment

In [2]:
import pandas as pd
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
index=['a', 'c', 'e', 'f', 'g'])
s1+s2


a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [7]:
import numpy as np
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
index=['Ohio', 'Texas', 'Colorado'])
df1


b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [9]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(df2)
print(df1+df2)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN


In [17]:
df=pd.DataFrame({'A':[1,2]})#If you add DataFrame objects with no column or row labels in common, the result will contain all nulls:
df1=pd.DataFrame({'B':[3,4]})
print(df)
print(df1)
print("*********")
print(df+df1)

   A
0  1
1  2
   B
0  3
1  4
*********
    A   B
0 NaN NaN
1 NaN NaN


# Arithmetic methods with fill values


In [24]:
df1 = pd.DataFrame(np.arange(12).reshape((3, 4)),
columns=list('abcd'))
print(df1)
df2 = pd.DataFrame(np.arange(20).reshape((4, 5)),
columns=['a','b','c','d','e'])
df2

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [27]:
df2.loc[1,'c']=0
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   0   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [28]:
print(df1+df2)

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0   6.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN


In [32]:
df1.add(df2,fill_value=3)#Using the add method on df1, I pass df2 and an argument to fill_value:jitnay number aap chaho layskty hu fill_value  mai

a     b     c     d     e
0   0.0   2.0   4.0   6.0   7.0
1   9.0  11.0   6.0  15.0  12.0
2  18.0  20.0  22.0  24.0  17.0
3  18.0  19.0  20.0  21.0  22.0

# Operations between DataFrame and Series

In [35]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [38]:
print(arr[0])
print("*******")
arr-arr[0]

[0. 1. 2. 3.]
*******


array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [4]:
import numpy as np
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [41]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [42]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [6]:
import pandas as pd
series3=pd.Series(range(3),index=list('bef'))
print(series3)


b    0
e    1
f    2
dtype: int64


In [7]:
frame+series3

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [10]:
series2 = frame['d']
print(series2)
print(frame)

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0


In [14]:
frame.sub(series2,axis="index")
#If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods. For example:


b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# Function Application and Mapping

In [3]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
print("********")
a=abs(frame)
print(a)

               b         d         e
Utah   -0.298743 -1.493394 -1.052622
Ohio    1.574673 -0.859962 -0.380777
Texas   0.943083 -1.335097 -1.742991
Oregon -0.736197 -0.919361  0.174866
********
               b         d         e
Utah    0.298743  1.493394  1.052622
Ohio    1.574673  0.859962  0.380777
Texas   0.943083  1.335097  1.742991
Oregon  0.736197  0.919361  0.174866


In [23]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.816273
d    3.867728
e    1.596310
dtype: float64

In [25]:
frame.apply(f, axis='columns')

Utah      2.784455
Ohio      1.406717
Texas     1.915470
Oregon    2.526670
dtype: float64

In [26]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.856771 -1.567168 -0.946543
max  0.959501  2.300560  0.649767

In [4]:
format = lambda x: '%.2f' % x
frame.applymap(format)
#Suppose you wanted to compute a formatted string from each floating-point value in frame. You can do this with applymap

b      d      e
Utah    -0.30  -1.49  -1.05
Ohio     1.57  -0.86  -0.38
Texas    0.94  -1.34  -1.74
Oregon  -0.74  -0.92   0.17

In [5]:
frame['e'].map(format)

Utah      -1.05
Ohio      -0.38
Texas     -1.74
Oregon     0.17
Name: e, dtype: object

# Sorting and Ranking

In [8]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
print(obj)
print(obj.sort_index())

d    0
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    0
dtype: int64


In [10]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
index=['three', 'one'],
columns=['d', 'a', 'b', 'c'])
frame.sort_index()#row wise sorting of index

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [11]:
frame.sort_index(axis=1)#columns wise sorting

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [12]:
frame.sort_index(axis=1, ascending=False)#it creates descending order

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [13]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()#sort values

2   -3
3    2
0    4
1    7
dtype: int64

In [15]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [16]:
frame.sort_values(by='a') #sort column a

b  a
0  4  0
2 -3  0
1  7  1
3  2  1

In [18]:
frame.sort_values(by=['a','b']) #sort all

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

# Axis Indexes with Duplicate Labels

In [2]:
import pandas as pd
import numpy as np
data=pd.Series(range(5),index=['a','a','b','b','c'])
data

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [4]:
print(data['a'])
print(data['c'])

a    0
a    1
dtype: int64
4


In [9]:
obj=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
print(obj)
print(obj.loc['b'])

          0         1         2
a -0.697629  0.240350 -1.669091
a -0.597312  0.286906 -1.557472
b -0.698251  3.553566 -1.167442
b -0.653081 -0.338335  0.361115
          0         1         2
b -0.698251  3.553566 -1.167442
b -0.653081 -0.338335  0.361115


# Summarizing and Computing Descriptive Statistics

In [18]:
df=pd.DataFrame([[1.23,np.nan],[1.32,4.34],[np.nan,np.nan],[2.2,3.21]],index=['a','b','c','d'],columns=['one','two'])
df

one   two
a  1.23   NaN
b  1.32  4.34
c   NaN   NaN
d  2.20  3.21

In [20]:
df.sum()

one    4.75
two    7.55
dtype: float64

In [21]:
df.sum(axis=1)#or axis=columns returns columns wise sum

a    1.23
b    5.66
c    0.00
d    5.41
dtype: float64

In [22]:
df.mean(axis='columns', skipna=False)#return mean where number exist


a      NaN
b    2.830
c      NaN
d    2.705
dtype: float64

In [23]:
df.cumsum()

one   two
a  1.23   NaN
b  2.55  4.34
c   NaN   NaN
d  4.75  7.55

In [ ]:
df.describe()

# Unique Values, Value Counts, and Membership



In [16]:
import pandas as pd
a=pd.Series(['a','a','b','b','c'])
#print(a)
#print(a.unique())
#print("*********")
#print(a.value_counts())
#pd.value_counts(a.values, sort=False)

c    1
a    2
b    2
dtype: int64

In [26]:
#mask = a.isin(['b', 'c'])
#print(mask)
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
 'Qu2': [2, 3, 1, 2, 3],
  'Qu3': [1, 5, 2, 4, 4]})
print(data)
#Passing pandas.value_counts to this DataFrame’s apply function gives:
data.apply(pd.value_counts).fillna(0)
#The values are the respective counts of these values in each column.



   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4


Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0